env:
  enableNotion: "False"  # TODO: change to true when correct secret token set

imageName: ""

web:
  replicasCount: 1
  memoryLimit: "1Gi"
  cpuLimit: "2"
  memoryRequest: "200Mi"
  cpuRequest: "0.2"

ingress:
  # reserved in GCP
  externalIpName: null
