ingress:
  # reserved in GCP, note the differences between loadbalanceR and loadbalance-staging (no R)
  externalIpName: loadbalancer

web:
  replicasCount: 2

env:
  staticUrl: "https://storage.googleapis.com/epidemics-covid/static/production"
  nodeEnv: "production"
