version: "3"

services:
  server:
    build:
      context: ./
    image: coron
    ports:
      - 8000:8000
    volumes:
      - ./src/:/usr/app/src/
    working_dir: /usr/app/src/server
    entrypoint:
      - uvicorn
      - --use-colors
      - main:app
      - --host
      - 0.0.0.0
      - --reload

  webpack:
    build:
      context: ./
      dockerfile: webpack.Dockerfile
    volumes: 
      - ./src/:/usr/app/src/
    working_dir: /usr/app
    entrypoint: yarn run webpack